### ISSUE TITLE
Config.AllowAnyoneToEdit not working 

### ISSUE THREAD

**Issue by Tttony2x** [BryceCanyonCounty/bcc-scene#11]
Recently we updated bcc-scene from 2.2.0 to 2.2.2 in order to fix some issues I saw were resolved, however this new one has cropped up. Even with Config.AllowAnyoneToEdit set to true, players cannot delete scenes unless they are the one who placed it. 

The relevant section of our config looks like this:
```
-- USE ONLY ONE OF THE BELOW --
Config.AllowAnyoneToEdit = true -- True or False
Config.AdminLock = false -- Use 'false' for no admin lock or IE group names. {'admin', 'god'}
Config.JobLock = false --{'police', 'doctor'} -- Use 'false' for no job lock or IE. {'police'}
```
The rest of the config is attached.
[config.zip](https://github.com/BryceCanyonCounty/bcc-scene/files/12286498/config.zip)

**Comment by engineeringtuna** [comment]
Adding onto this, I was peeking through the code. 

AllowAnyoneToEdit is used in the client so it's needed
AllowAnyoneToDelete is used in the server but is not in the config. 

I just added the AllowAnyoneToDelete = true to our config and I'll report back if it works!

EDIT: 

This did work.

**Comment by AndrewR3K** [comment]
Thanks for the PR. This should be resolved now.
